### ISSUE TITLE
platform for communicating off of github

### ISSUE THREAD

**Issue by mainmachine** [livkx/cadmus#11]
@livkx We need a companion platform for off-github communication... slack, discourse, telegram...?

Some topics don't makes sense as issues or commits, for instance the **develop** branch is behind **master**, which is generally not correct. I've merged master into develop locally but I don't want to push it here without discussing it first, seeing as how we've just begun our collaboration recently. :wink:

**Comment by livkx** [comment]
@mainmachine Hey man, sorry been quite busy with work recently but I still fully intend on maintaining this, Discord works fine for me, my addy is livkx#7230
